# Advanced usage example with multiple scan modes and custom configuration
# Copy this workflow to .github/workflows/ in your repository

name: Advanced Action Dependency Scanner

on:
  pull_request:
    paths: ['**/*.md', 'docs/**']
    types: [opened, synchronize, reopened]
  push:
    branches: [main, master]
    paths: ['**/*.md']
  workflow_dispatch:
    inputs:
      action-to-scan:
        description: 'Action to scan (org/action@ref format)'
        required: true
        default: 'actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955'

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  # Scan PR changes with custom settings
  scan-pr:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
      
      - name: Scan PR Dependencies
        id: pr-scan
        uses: username/recursive-action-scanner@v1
        with:
          mode: pr
          pr-number: ${{ github.event.pull_request.number }}
          max-depth: 8
          output-format: json
          comment-title: "🔍 Action Dependency Analysis Report"
      
      - name: Upload PR Scan Results
        if: steps.pr-scan.outputs.scan-success == 'true'
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: pr-scan-results-${{ github.event.pull_request.number }}
          path: |
            results.json
            results.txt

  # Scan commits on main branch
  scan-commit:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
      
      - name: Scan Latest Commit
        id: commit-scan
        uses: username/recursive-action-scanner@v1
        with:
          mode: commit
          commit-sha: ${{ github.sha }}
          max-depth: 5
          post-comment: false
          output-format: text
      
      - name: Create Issue for Large Dependency Trees
        if: steps.commit-scan.outputs.total-actions > 20
        uses: actions/github-script@5c56fde4671bc2d3592fb0f2c5b5bab9ddae03b1
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Large Action Dependency Tree Detected (${steps.commit-scan.outputs.total-actions} actions)`,
              body: `The latest commit introduced a large number of action dependencies.
              
              **Summary:**
              - Total actions: ${{ steps.commit-scan.outputs.total-actions }}
              - Root actions: ${{ steps.commit-scan.outputs.root-actions }}
              - Commit: ${{ github.sha }}
              
              Please review if this is expected.`,
              labels: ['dependencies', 'review-needed']
            })

  # Manual scan of specific action
  scan-specific-action:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
      
      - name: Scan Specific Action
        uses: username/recursive-action-scanner@v1
        with:
          mode: action
          action-reference: ${{ github.event.inputs.action-to-scan }}
          max-depth: 10
          output-format: json
      
      - name: Display Results
        run: |
          echo "Scan completed for: ${{ github.event.inputs.action-to-scan }}"
          echo "Check the action outputs for detailed results"