# Basic usage example for other repositories
# Copy this workflow to .github/workflows/ in your repository

name: Action Dependency Scanner

on:
  pull_request:
    paths: ['**/*.md']
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  scan-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Scan Action Dependencies
        uses: username/recursive-action-scanner@v1
        with:
          mode: pr
          pr-number: ${{ github.event.pull_request.number }}
          post-comment: true